export const COUNTRY_PHONE_CODES = [
  { countryName: 'Afghanistan', code: '+93' },
  { countryName: 'Albania', code: '+355' },
  { countryName: 'Algeria', code: '+213' },
  { countryName: 'Andorra', code: '+376' },
  { countryName: 'Angola', code: '+244' },
  { countryName: 'Antigua and Barbuda', code: '+1-268' },
  { countryName: 'Argentina', code: '+54' },
  { countryName: 'Armenia', code: '+374' },
  { countryName: 'Australia', code: '+61' },
  { countryName: 'Austria', code: '+43' },
  { countryName: 'Azerbaijan', code: '+994' },
  { countryName: 'Bahamas', code: '+1-242' },
  { countryName: 'Bahrain', code: '+973' },
  { countryName: 'Bangladesh', code: '+880' },
  { countryName: 'Barbados', code: '+1-246' },
  { countryName: 'Belarus', code: '+375' },
  { countryName: 'Belgium', code: '+32' },
  { countryName: 'Belize', code: '+501' },
  { countryName: 'Benin', code: '+229' },
  { countryName: 'Bhutan', code: '+975' },
  { countryName: 'Bolivia', code: '+591' },
  { countryName: 'Bosnia and Herzegovina', code: '+387' },
  { countryName: 'Botswana', code: '+267' },
  { countryName: 'Brazil', code: '+55' },
  { countryName: 'Brunei', code: '+673' },
  { countryName: 'Bulgaria', code: '+359' },
  { countryName: 'Burkina Faso', code: '+226' },
  { countryName: 'Burundi', code: '+257' },
  { countryName: 'Cabo Verde', code: '+238' },
  { countryName: 'Cambodia', code: '+855' },
  { countryName: 'Cameroon', code: '+237' },
  { countryName: 'Canada', code: '+1' },
  { countryName: 'Central African Republic', code: '+236' },
  { countryName: 'Chad', code: '+235' },
  { countryName: 'Chile', code: '+56' },
  { countryName: 'China', code: '+86' },
  { countryName: 'Colombia', code: '+57' },
  { countryName: 'Comoros', code: '+269' },
  { countryName: 'Congo (Congo-Brazzaville)', code: '+242' },
  { countryName: 'Costa Rica', code: '+506' },
  { countryName: 'Croatia', code: '+385' },
  { countryName: 'Cuba', code: '+53' },
  { countryName: 'Cyprus', code: '+357' },
  { countryName: 'Czech Republic', code: '+420' },
  { countryName: 'Democratic Republic of the Congo', code: '+243' },
  { countryName: 'Denmark', code: '+45' },
  { countryName: 'Djibouti', code: '+253' },
  { countryName: 'Dominican Republic', code: '+1-809' },
  { countryName: 'Ecuador', code: '+593' },
  { countryName: 'Egypt', code: '+20' },
  { countryName: 'El Salvador', code: '+503' },
  { countryName: 'Equatorial Guinea', code: '+240' },
  { countryName: 'Eritrea', code: '+291' },
  { countryName: 'Estonia', code: '+372' },
  { countryName: 'Eswatini', code: '+268' },
  { countryName: 'Ethiopia', code: '+251' },
  { countryName: 'Fiji', code: '+679' },
  { countryName: 'Finland', code: '+358' },
  { countryName: 'France', code: '+33' },
  { countryName: 'Germany', code: '+49' },
  { countryName: 'Ghana', code: '+233' },
  { countryName: 'India', code: '+91' },
  { countryName: 'Indonesia', code: '+62' },
  { countryName: 'Ireland', code: '+353' },
  { countryName: 'Italy', code: '+39' },
  { countryName: 'Japan', code: '+81' },
  { countryName: 'Kenya', code: '+254' },
  { countryName: 'Malaysia', code: '+60' },
  { countryName: 'Mexico', code: '+52' },
  { countryName: 'Netherlands', code: '+31' },
  { countryName: 'Nigeria', code: '+234' },
  { countryName: 'Pakistan', code: '+92' },
  { countryName: 'Philippines', code: '+63' },
  { countryName: 'Russia', code: '+7' },
  { countryName: 'South Africa', code: '+27' },
  { countryName: 'United Kingdom', code: '+44' },
  { countryName: 'United States', code: '+1' },
  { countryName: 'Vietnam', code: '+84' },
  { countryName: 'Zimbabwe', code: '+263' },
];
